# Generated by Django 4.0.5 on 2022-07-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='receiver_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receiver_email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
